/**
 * Bot Skill — schema dùng chung giữa:
 *  - BotSkillBuilder (factory)
 *  - backtestEngine (backtest)
 *  - local_agent (ADK FunctionTool runtime)
 */

import type { IndicatorType, FilterBlock } from '../agent/backtestEngine';
export type { FilterBlock } from '../agent/backtestEngine';

export interface BotSkillConfig {
  // ── Metadata ──
  name: string;
  description: string;
  version: string;
  createdAt: string;

  // ── Entry Signal ──
  signal: IndicatorType;
  // EA-style extra AND-filters layered on top of the entry signal (optional).
  filters?: FilterBlock[];
  // Supertrend EA inputs (used by 'supertrend' / 'supertrend_flip' signals)
  supertrendPeriod?: number;  // ATR period, default 10
  supertrendMult?: number;    // ATR multiplier, default 3
  // Range-breakout EA inputs ('range_breakout' signal)
  breakoutPeriod?: number;    // Donchian lookback bars, default 20
  // EA time-stop: force-close after N bars in a trade (0 = off)
  maxBarsInTrade?: number;
  // MTF trend filter: HTF Supertrend gates entry direction (green=buy-only)
  htfMinutes?: number;            // e.g. 240 = H4 trend filter
  htfSupertrendPeriod?: number;   // default 10
  htfSupertrendMult?: number;     // default 3

  // ── Risk Management ──
  takeProfitPct: number;
  stopLossPct: number;
  trailingStopPct: number;
  enableTrailing: boolean;
  enableDefense: boolean;

  // ── Position Sizing ──
  leverage: number;
  orderPct: number;     // % of capital mỗi lệnh
  commission: number;   // % phí trade mỗi chiều

  // ── Direction Filter ──
  direction: 'both' | 'long_only' | 'short_only';

  // ── EA money-management module (MT4/MT5-style; all optional) ──
  // Identical names in BacktestConfig and LiveBotConfig — one set of rules
  // runs in the backtester AND the live bot, so results stay comparable.
  sizingMode?:          'fixed_pct' | 'risk_pct';
  riskPct?:             number;  // % capital risked per trade (risk_pct mode)
  breakEvenTriggerPct?: number;  // move SL to entry after +X% in favor (0 = off)
  cooldownBars?:        number;  // bars to wait after a closed trade
  maxConsecLosses?:     number;  // pause entries after N straight losses (0 = off)
  maxDailyLossPct?:     number;  // pause entries for the day at -X% (0 = off)
  sessionStartHour?:    number;  // UTC trading session start (0-23)
  sessionEndHour?:      number;  // UTC trading session end (0-23)
  slippagePct?:         number;  // backtest realism: adverse slippage per fill

  // ── Author (Sui address that receives the 0.005 SUI per-OPEN fee in Live Trade) ──
  // For PRESET_SKILLS: the dev/publisher wallet.
  // For user-created skills: the wallet that built it (set on publish).
  // For marketplace-bought skills: the original on-chain `creator` from SkillPublished.
  authorAddress?: string;

  // ── Preferred Backtest Defaults (set by research presets) ──
  preferredTimeframe?: string;   // e.g. 'M30' — pre-fills TF selector
  preferredAsset?: string;       // e.g. 'sui' — pre-selects asset

  // ── Backtest Stats (cập nhật sau khi test) ──
  lastStats?: {
    winRate: number;
    profitFactor: number;
    sharpeRatio: number;
    netProfitPct: number;
    maxDrawdownPct: number;
    totalTrades: number;
    testedAt: string;
    timeframe: string;
    duration: string;
    asset?: string;
  };
}

// Nhãn hiển thị
export const SIGNAL_LABELS: Record<IndicatorType, string> = {
  ema_cross: 'EMA Cross (9/21)',
  rsi:       'RSI Momentum (30/70)',
  macd:      'MACD Histogram',
  bb:        'Bollinger Bands',
  rsi_macd:  'RSI + MACD Hybrid',
  supertrend:'Supertrend (10, 3)',
  supertrend_flip:'Supertrend Flip (10, 3) — EA',
  range_breakout:'Range Breakout (Donchian) — EA',
};

export const DIRECTION_LABELS: Record<BotSkillConfig['direction'], string> = {
  both:        '↕ Both Long & Short',
  long_only:   '↑ Long only (Mua)',
  short_only:  '↓ Short only (sell)',
};

// localStorage key
export const BOT_SKILLS_KEY = 'suirobo_bot_skills';

// Dev/publisher wallet that authored the AI-researched presets.
// Receives the 0.005 SUI author share whenever a Live Trade Auto Bot opens a
// position using one of these presets.
export const DEV_WALLET_ADDRESS = '0xafbc48fd349fb44ce9c6f2b33423e6ae7c826d53a25920a0d4c3c475e40889c5';

// ── AI-Researched Presets ─────────────────────────────────────────────────────
// Generated by sweep_sui_stable.mjs over 10,080 combos × Jan–Jun 2025 SUI data.
// Filter: profit > 0 every month, MaxDD < 20% over 3m.
export const PRESET_SKILLS: BotSkillConfig[] = [
  {
    name: 'sui_alpha_m30',
    description:
      'SUI/USDC RSI+MACD Confluence on M30 · Every month positive Jan–Jun 2025 · ' +
      '+114.5% in 6m / MaxDD 12.7% · AI-researched from 10,080 combos.',
    version: '1.0.0',
    createdAt: '2026-06-08',
    signal: 'rsi_macd',
    takeProfitPct: 10,
    stopLossPct: 0.5,
    trailingStopPct: 0,
    enableTrailing: false,
    enableDefense: true,
    leverage: 5,
    orderPct: 50,
    commission: 0.01,
    direction: 'both',
    authorAddress: DEV_WALLET_ADDRESS,
    preferredTimeframe: 'M30',
    preferredAsset: 'sui',
    lastStats: {
      winRate: 12.5,
      profitFactor: 2.86,
      sharpeRatio: 0,
      netProfitPct: 114.5,
      maxDrawdownPct: 12.7,
      totalTrades: 56,
      testedAt: '2026-06-08',
      timeframe: 'M30',
      duration: '6m',
      asset: 'SUI/USDT',
    },
  },
  {
    name: 'sui_ema_h1',
    description:
      'SUI/USDC EMA Cross on H1 · Stable across 6 months · ' +
      '+48.2% in 1m / +69.1% in 6m / MaxDD 17.7% · Conservative 2x leverage.',
    version: '1.0.0',
    createdAt: '2026-06-08',
    signal: 'ema_cross',
    takeProfitPct: 15,
    stopLossPct: 1,
    trailingStopPct: 0,
    enableTrailing: false,
    enableDefense: true,
    leverage: 2,
    orderPct: 50,
    commission: 0.01,
    direction: 'both',
    authorAddress: DEV_WALLET_ADDRESS,
    preferredTimeframe: 'H1',
    preferredAsset: 'sui',
    lastStats: {
      winRate: 17.8,
      profitFactor: 2.52,
      sharpeRatio: 0,
      netProfitPct: 69.1,
      maxDrawdownPct: 17.7,
      totalTrades: 181,
      testedAt: '2026-06-08',
      timeframe: 'H1',
      duration: '6m',
      asset: 'SUI/USDT',
    },
  },
  {
    name: 'sui_supertrend_m5_v2',
    description: '[BOT|profit=12.0|maxdd=12.6|wr=36.8|pf=1.21|trades=57|tf=M5|lev=3] SUI Supertrend Flip EA v2 — classic EA flip entry ST(20,5), short side, 16-24h UTC session, TP3/SL1.5, 6-bar cooldown. Profitable EVERY month Jan-May 2026 on real Binance M5 data, costed at 0.05% fee + 0.05% slippage per side.',
    version: '2.0.0',
    createdAt: '2026-06-12',
    signal: 'supertrend_flip',          // one entry per trend leg (EA standard), not the v1 wick-catch
    supertrendPeriod: 20,
    supertrendMult: 5,
    takeProfitPct: 3,
    stopLossPct: 1.5,
    trailingStopPct: 0,
    enableTrailing: false,
    enableDefense: true,
    leverage: 3,
    orderPct: 50,
    commission: 0.05,
    slippagePct: 0.05,
    direction: 'short_only',
    cooldownBars: 6,
    sessionStartHour: 16,               // 16:00–24:00 UTC entry window
    sessionEndHour: 0,
    authorAddress: DEV_WALLET_ADDRESS,
    preferredTimeframe: 'M5',
    preferredAsset: 'sui',
    lastStats: {
      winRate: 36.8,
      profitFactor: 1.21,
      sharpeRatio: 0.05,
      netProfitPct: 12.0,
      maxDrawdownPct: 12.6,
      totalTrades: 57,
      testedAt: '2026-06-12',
      timeframe: 'M5',
      duration: '5m (Jan-May 2026)',
      asset: 'SUI/USDT',
    },
  },
  {
    name: 'sui_mtf_supertrend_m5',
    description: '[BOT|profit=5.4|maxdd=15.8|wr=44.1|pf=1.35|trades=127|tf=M5|lev=2] SUI MTF Supertrend EA — H4 Supertrend(10,3) gates direction (green=buy-only, red=sell-only), M5 Supertrend Flip(200,6) fires entries, trailing runner SL2%/TR2.5% (no TP cap), 16h cooldown. Mar-Sep 2025 standalone-month avg +5.4%/mo (6/7 months positive); full-12-month avg still +1.3%/mo. Real Binance M5 data, 0.05% fee + 0.05% slippage per side.',
    version: '1.0.0',
    createdAt: '2026-06-13',
    signal: 'supertrend_flip',
    supertrendPeriod: 200,
    supertrendMult: 6,
    htfMinutes: 240,                 // H4 trend gate (closed candles only)
    htfSupertrendPeriod: 10,
    htfSupertrendMult: 3,
    takeProfitPct: 999,              // runner: no TP cap — trailing locks profits
    stopLossPct: 2,
    trailingStopPct: 2.5,
    enableTrailing: true,
    enableDefense: true,
    leverage: 2,
    orderPct: 50,
    commission: 0.05,
    slippagePct: 0.05,
    direction: 'both',               // the H4 gate decides long/short
    cooldownBars: 192,               // 16h between entries on M5
    authorAddress: DEV_WALLET_ADDRESS,
    preferredTimeframe: 'M5',
    preferredAsset: 'sui',
    lastStats: {
      winRate: 44.1,
      profitFactor: 1.35,
      sharpeRatio: 0,
      netProfitPct: 37.8,            // Mar-Sep compounded reference
      maxDrawdownPct: 15.8,
      totalTrades: 127,
      testedAt: '2026-06-13',
      timeframe: 'M5',
      duration: '7m (Mar-Sep 2025)',
      asset: 'SUI/USDT',
    },
  },
  {
    name: 'btc_breakout_m15',
    description: '[BOT|profit=45.9|maxdd=15.2|wr=50.0|pf=1.63|trades=56|tf=M15|lev=2] BTC Range-Breakout EA — Donchian(96) short-side breakout, Asia session 00-08h UTC, TP2/SL1, 8-bar cooldown, 2% risk-per-trade sizing. Architecture from the Gold→Bitcoin EA research blueprint. +45.9% over FULL YEAR 2025 real Binance M15 data (9/12 months positive), costed at 0.05% fee + 0.05% slippage per side.',
    version: '1.0.0',
    createdAt: '2026-06-12',
    signal: 'range_breakout',
    breakoutPeriod: 96,                 // prior 24h range on M15
    takeProfitPct: 2,
    stopLossPct: 1,
    trailingStopPct: 0,
    enableTrailing: false,
    enableDefense: true,
    leverage: 2,
    orderPct: 50,
    commission: 0.05,
    slippagePct: 0.05,
    direction: 'short_only',
    sizingMode: 'risk_pct',
    riskPct: 2,                         // PDF blueprint: ≤2% capital risked per trade
    cooldownBars: 8,
    sessionStartHour: 0,                // Asia liquidity window
    sessionEndHour: 8,
    authorAddress: DEV_WALLET_ADDRESS,
    preferredTimeframe: 'M15',
    preferredAsset: 'btc',
    lastStats: {
      winRate: 50.0,
      profitFactor: 1.63,
      sharpeRatio: 0.15,
      netProfitPct: 45.9,
      maxDrawdownPct: 15.2,
      totalTrades: 56,
      testedAt: '2026-06-12',
      timeframe: 'M15',
      duration: '12m (full 2025)',
      asset: 'BTC/USDT',
    },
  },
  {
    name: 'sui_supertrend_m5',
    description: '[LEGACY|tf=M5|lev=10] Superseded by sui_supertrend_m5_v2. v1 wick-catch entry re-tested on real Jan-May 2026 M5 data with fees+slippage: NOT profitable. Kept for reference only.',
    version: '1.0.0',
    createdAt: '2026-06-10',
    signal: 'supertrend', // Updated to use the actual supertrend logic
    takeProfitPct: 8,
    stopLossPct: 1.5,
    trailingStopPct: 0,
    enableTrailing: false,
    enableDefense: true,
    leverage: 10,
    orderPct: 50,
    commission: 0.01,
    direction: 'both',
    authorAddress: DEV_WALLET_ADDRESS,
    preferredTimeframe: 'M5',
    preferredAsset: 'sui',
    lastStats: {
      winRate: 15.5,
      profitFactor: 3.1,
      sharpeRatio: 0,
      netProfitPct: 128.5,
      maxDrawdownPct: 8.2,
      totalTrades: 82,
      testedAt: '2026-06-10',
      timeframe: 'M5',
      duration: '6m',
      asset: 'SUI/USDT',
    },
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function loadBotSkills(): BotSkillConfig[] {
  try {
    const raw = localStorage.getItem(BOT_SKILLS_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

export function saveBotSkills(skills: BotSkillConfig[]): void {
  localStorage.setItem(BOT_SKILLS_KEY, JSON.stringify(skills));
}

export function upsertBotSkill(skill: BotSkillConfig): BotSkillConfig[] {
  const all = loadBotSkills();
  const idx = all.findIndex(s => s.name === skill.name);
  if (idx >= 0) all[idx] = skill; else all.push(skill);
  saveBotSkills(all);
  return all;
}

export function deleteBotSkill(name: string): BotSkillConfig[] {
  const all = loadBotSkills().filter(s => s.name !== name);
  saveBotSkills(all);
  return all;
}

/** Tạo SKILL.md content từ BotSkillConfig */
export function generateSkillMd(skill: BotSkillConfig): string {
  return `---
name: ${skill.name}
description: ${skill.description}
version: ${skill.version}
type: bot
signal: ${skill.signal}
takeProfitPct: ${skill.takeProfitPct}
stopLossPct: ${skill.stopLossPct}
trailingStopPct: ${skill.trailingStopPct}
enableTrailing: ${skill.enableTrailing}
enableDefense: ${skill.enableDefense}
leverage: ${skill.leverage}
orderPct: ${skill.orderPct}
commission: ${skill.commission}
direction: ${skill.direction}
createdAt: ${skill.createdAt}
---

# ${skill.name}

${skill.description}

## Strategy

- **Entry signal:** ${SIGNAL_LABELS[skill.signal]}
- **Trade direction:** ${DIRECTION_LABELS[skill.direction]}
- **Take Profit:** ${skill.takeProfitPct}%
- **Stop Loss:** ${skill.stopLossPct}%
- **Trailing Stop:** ${skill.enableTrailing ? skill.trailingStopPct + '%' : 'Off'}
- **Leverage:** ${skill.leverage}x
- **Order size:** ${skill.orderPct}% of capital
- **Fee:** ${skill.commission}% per side

## Compatibility

This skill was generated by the Suirobo Bot Skill Builder.
It can be used directly in Backtest or executed by the agent.
`;
}

/** Tạo index.js ADK FunctionTool từ BotSkillConfig */
export function generateIndexJs(skill: BotSkillConfig): string {
  const signalLogic: Record<IndicatorType, string> = {
    ema_cross: `
  // EMA Cross: ema9 vượt lên trên ema21 → BUY; ema9 xuống dưới ema21 → SELL
  if (prev_ema9 <= prev_ema21 && ema9 > ema21) signal = 'BUY';
  else if (prev_ema9 >= prev_ema21 && ema9 < ema21) signal = 'SELL';`,
    rsi: `
  // RSI: vượt lên 30 từ dưới → BUY; vụt xuống 70 từ trên → SELL
  if (prev_rsi < 30 && rsi >= 30) signal = 'BUY';
  else if (prev_rsi > 70 && rsi <= 70) signal = 'SELL';`,
    macd: `
  // MACD Histogram: từ âm sang dương → BUY; từ dương sang âm → SELL
  if (prev_histogram <= 0 && histogram > 0) signal = 'BUY';
  else if (prev_histogram >= 0 && histogram < 0) signal = 'SELL';`,
    bb: `
  // Bollinger Bands: giá cắt lên dải dưới → BUY; giá cắt xuống dải trên → SELL
  if (prev_close <= bb_lower && close > bb_lower) signal = 'BUY';
  else if (prev_close >= bb_upper && close < bb_upper) signal = 'SELL';`,
    rsi_macd: `
  // RSI + MACD Hybrid
  if (rsi < 40 && prev_histogram <= 0 && histogram > 0) signal = 'BUY';
  else if (rsi > 60 && prev_histogram >= 0 && histogram < 0) signal = 'SELL';`,
    supertrend: `
  // Supertrend Pullback Logic (Bắt râu)
  if (supertrend_dir === 1 && low <= supertrend * 1.01 && low > supertrend) signal = 'BUY';
  else if (supertrend_dir === -1 && high >= supertrend * 0.99 && high < supertrend) signal = 'SELL';`,
    supertrend_flip: `
  // Classic Supertrend EA flip: enter only on the trend-direction change bar
  if (prev_supertrend_dir === -1 && supertrend_dir === 1) signal = 'BUY';
  else if (prev_supertrend_dir === 1 && supertrend_dir === -1) signal = 'SELL';`,
    range_breakout: `
  // Donchian momentum breakout: close crosses the prior N-bar extreme
  if (close > donchian_high_prev && prev_close <= donchian_high_prev2) signal = 'BUY';
  else if (close < donchian_low_prev && prev_close >= donchian_low_prev2) signal = 'SELL';`,
  };

  const directionFilter = skill.direction === 'long_only'
    ? "  if (signal === 'SELL') signal = 'HOLD'; // long_only"
    : skill.direction === 'short_only'
    ? "  if (signal === 'BUY') signal = 'HOLD'; // short_only"
    : '';

  return `/**
 * Bot Skill: ${skill.name}
 * Tạo tự động bởi Suirobo Bot Skill Builder
 * Tương thích: ADK FunctionTool + Backtest Engine
 */
const { FunctionTool, z } = globalThis.__SUIROBO_REGISTRY__;

export const skill = new FunctionTool({
  name: '${skill.name}',
  description: '${skill.description}',
  parameters: z.object({
    close: z.number().describe('Current close price'),
    low: z.number().optional().describe('Current low price'),
    high: z.number().optional().describe('Current high price'),
    prev_close: z.number().optional().describe('Previous candle close'),
    ema9: z.number().optional().describe('EMA 9'),
    ema21: z.number().optional().describe('EMA 21'),
    prev_ema9: z.number().optional().describe('Previous candle EMA 9'),
    prev_ema21: z.number().optional().describe('Previous candle EMA 21'),
    rsi: z.number().optional().describe('RSI 14'),
    prev_rsi: z.number().optional().describe('Previous candle RSI'),
    histogram: z.number().optional().describe('MACD Histogram'),
    prev_histogram: z.number().optional().describe('Previous candle MACD histogram'),
    bb_upper: z.number().optional().describe('Bollinger Upper'),
    bb_lower: z.number().optional().describe('Bollinger Lower'),
    supertrend: z.number().optional().describe('Supertrend Line'),
    supertrend_dir: z.number().optional().describe('Supertrend Direction (1 = UP, -1 = DOWN)'),
  })
}, async function ${skill.name.replace(/[^a-z0-9_]/gi, '_')}(params) {
  const {
    close, low = close, high = close, prev_close = close,
    ema9 = close, ema21 = close,
    prev_ema9 = ema9, prev_ema21 = ema21,
    rsi = 50, prev_rsi = 50,
    histogram = 0, prev_histogram = 0,
    bb_upper = close * 1.05, bb_lower = close * 0.95,
    supertrend = close, supertrend_dir = 1,
  } = params;

  let signal = 'HOLD';
  ${signalLogic[skill.signal]}
  ${directionFilter}

  const tp = signal === 'BUY'
    ? close * (1 + ${skill.takeProfitPct} / 100)
    : close * (1 - ${skill.takeProfitPct} / 100);
  const sl = signal === 'BUY'
    ? close * (1 - ${skill.stopLossPct} / 100)
    : close * (1 + ${skill.stopLossPct} / 100);

  return {
    signal,
    strategy: '${SIGNAL_LABELS[skill.signal]}',
    direction: '${skill.direction}',
    entryPrice: close,
    takeProfitPrice: Math.round(tp),
    stopLossPrice: Math.round(sl),
    leverage: ${skill.leverage},
    orderPct: ${skill.orderPct},
    note: signal !== 'HOLD'
      ? \`\${signal} @ \$\${close.toLocaleString()} | TP: \$\${Math.round(tp).toLocaleString()} | SL: \$\${Math.round(sl).toLocaleString()}\`
      : 'Waiting for signal...',
  };
});

export default skill;
`;
}
